//! Christmas snowfall overlay effect.
//!
//! The snow is rendered without any external assets: a transparent PNG tile is
//! procedurally generated by this module and then scrolled over the finished
//! slideshow by FFmpeg.
//!
//! The tile is `TILE_REPEATS` panels wide and high while the pattern repeats
//! every `TILE_REPEATS - 1` panels. Scrolling by that period therefore keeps
//! the loop perfectly seamless and endless, and the extra panel guarantees the
//! frame stays covered so no edge can ever cut off the snow.
//!
//! Several layers with different speeds, wind directions and sway phases are
//! composited together. A single scrolling layer would move all of its flakes
//! as one rigid block, so the parallax between the layers is what makes the
//! result read as individual snowflakes falling at their own pace.

use anyhow::{bail, Context, Result};
use image::{Rgba, RgbaImage};
use log::debug;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

/// Panel sizes larger than this are downscaled before the flakes are drawn.
/// The generated tile is scaled back to its exact size by FFmpeg, which keeps
/// memory usage and PNG encoding time bounded on 4K renders.
const MAX_PANEL_DIMENSION: u32 = 1920;

/// Tile size in panels, per axis. The pattern repeats every `TILE_REPEATS - 1`
/// panels, so the one extra panel both covers the frame at every scroll offset
/// and hides the repetition behind a much longer period.
const TILE_REPEATS: u32 = 3;

/// Frame rate used for the generated snow layers.
const SNOW_FRAME_RATE: u32 = 30;

/// Label the slideshow stream is written to before the snow is composited on.
const SNOW_INPUT_LABEL: &str = "snowbase";

/// Label of the composited stream the generator encodes.
const SNOW_OUTPUT_LABEL: &str = "outv";

/// Vertical fall speed in panel heights per second when `speed` is `1.0`,
/// which makes a flake cross the screen in about 8 seconds. Snow drifts, it
/// does not rush, so this is deliberately unhurried.
const FALL_RATE: f32 = 0.12;

/// Horizontal drift speed in panel widths per second when `wind` is `1.0`.
const DRIFT_RATE: f32 = 0.06;

/// Sway amplitude in panel widths, applied on top of the linear drift. Without
/// it every flake of a layer would travel in a perfectly straight line.
const SWAY_AMOUNT: f32 = 0.035;

/// Sway cycles per second. Deliberately slow and incommensurate between the
/// layers so the layers never line up into a visible rhythm.
const SWAY_RATE: f32 = 0.11;

/// Smallest snowflake radius in pixels, so flakes stay visible even on tiny
/// videos where the size scaling shrinks them below a pixel.
const MIN_FLAKE_RADIUS: f32 = 1.0;

/// Number of snowflakes drawn per layer even on very small videos.
const MIN_FLAKES_PER_LAYER: usize = 12;

/// The snow layers, ordered from the distant background to the foreground.
///
/// Four layers with different speeds, wind directions and sway phases are what
/// make the motion look like individual flakes instead of a sliding texture:
/// the layers drift past each other, so no two flakes share a trajectory even
/// though each layer on its own is a simple scrolling tile.
const LAYER_SPECS: [SnowLayerSpec; 4] = [
    SnowLayerSpec {
        size_factor: 0.45,
        opacity_factor: 0.5,
        speed_factor: 0.55,
        wind_factor: -0.7,
        density_factor: 0.55,
        sway_phase: 0.0,
    },
    SnowLayerSpec {
        size_factor: 0.7,
        opacity_factor: 0.75,
        speed_factor: 0.8,
        wind_factor: 0.45,
        density_factor: 0.75,
        sway_phase: 2.4,
    },
    SnowLayerSpec {
        size_factor: 0.85,
        opacity_factor: 0.85,
        speed_factor: 1.05,
        wind_factor: -0.25,
        density_factor: 0.9,
        sway_phase: 4.1,
    },
    SnowLayerSpec {
        size_factor: 1.0,
        opacity_factor: 1.0,
        speed_factor: 1.3,
        wind_factor: 0.15,
        density_factor: 1.0,
        sway_phase: 5.6,
    },
];

/// Configuration of the Christmas snowfall overlay.
///
/// # Example
///
/// ```rust,no_run
/// use slideshow_generator::{SlideshowOptions, SnowfallOptions};
///
/// let snowfall = SnowfallOptions::new().with_density(45.0).with_wind(0.6);
/// let options = SlideshowOptions::new().with_snowfall(Some(snowfall));
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct SnowfallOptions {
    /// Number of snowflakes per megapixel of a panel, per layer.
    pub density: f32,
    /// Multiplier for the falling speed of the snow.
    pub speed: f32,
    /// Horizontal drift. Positive values blow the snow to the right.
    pub wind: f32,
    /// Diameter of a snowflake in pixels for a 1080p video.
    pub flake_size: f32,
    /// Opacity of the snow, between `0.0` and `1.0`.
    pub opacity: f32,
    /// Seed of the random generator, making the pattern reproducible.
    pub seed: u64,
}

impl Default for SnowfallOptions {
    fn default() -> Self {
        Self {
            density: 200.0,
            speed: 1.0,
            wind: 0.3,
            flake_size: 8.0,
            opacity: 0.85,
            seed: 0x5EED_5EED,
        }
    }
}

impl SnowfallOptions {
    /// Create a new snowfall configuration with default values
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the snowflake density per megapixel, per layer
    pub fn with_density(mut self, density: f32) -> Self {
        self.density = density;
        self
    }

    /// Set the falling speed multiplier
    pub fn with_speed(mut self, speed: f32) -> Self {
        self.speed = speed;
        self
    }

    /// Set the horizontal wind, negative values blow the snow to the left
    pub fn with_wind(mut self, wind: f32) -> Self {
        self.wind = wind;
        self
    }

    /// Set the snowflake diameter in pixels for a 1080p video
    pub fn with_flake_size(mut self, flake_size: f32) -> Self {
        self.flake_size = flake_size;
        self
    }

    /// Set the snow opacity between `0.0` and `1.0`
    pub fn with_opacity(mut self, opacity: f32) -> Self {
        self.opacity = opacity;
        self
    }

    /// Set the random seed used to place the snowflakes
    pub fn with_seed(mut self, seed: u64) -> Self {
        self.seed = seed;
        self
    }

    /// Validate the snowfall parameters
    ///
    /// # Example
    ///
    /// ```rust
    /// use slideshow_generator::SnowfallOptions;
    ///
    /// assert!(SnowfallOptions::new().validate().is_ok());
    /// assert!(SnowfallOptions::new().with_density(-1.0).validate().is_err());
    /// ```
    pub fn validate(&self) -> Result<()> {
        let checks: [(f32, f32, f32, &str); 5] = [
            (self.density, 0.0, 5000.0, "snowfall density"),
            (self.speed, 0.05, 20.0, "snowfall speed"),
            (self.wind, -10.0, 10.0, "snowfall wind"),
            (self.flake_size, 0.5, 100.0, "snowfall flake size"),
            (self.opacity, 0.0, 1.0, "snowfall opacity"),
        ];

        for (value, min, max, name) in checks {
            if !value.is_finite() || value < min || value > max {
                bail!("{} must be between {} and {}, got: {}", name, min, max, value);
            }
        }

        Ok(())
    }
}

/// Relative parameters of a single snow layer, derived from [`SnowfallOptions`]
#[derive(Debug, Clone, Copy)]
struct SnowLayerSpec {
    size_factor: f32,
    opacity_factor: f32,
    speed_factor: f32,
    /// Signed multiplier on the user facing `wind`, so layers blow in different
    /// directions and the snow does not sweep across as one block
    wind_factor: f32,
    density_factor: f32,
    /// Phase offset in radians, so the layers do not sway in unison
    sway_phase: f32,
}

/// A single generated snow layer, ready to be fed to FFmpeg
#[derive(Debug, Clone)]
pub struct SnowflakeLayer {
    /// Path of the generated, seamlessly tileable RGBA PNG
    pub tile: PathBuf,
    /// Label of this layer inside the filter graph
    pub label: String,
    /// Horizontal scroll speed, in panel widths per second
    pub velocity_x: f32,
    /// Vertical scroll speed, in panel heights per second
    pub velocity_y: f32,
    /// Horizontal sway amplitude, in panel widths
    pub sway_amplitude: f32,
    /// Sway phase offset in radians
    pub sway_phase: f32,
}

/// A prepared snowfall overlay: generated tiles plus the filter chain and the
/// FFmpeg inputs needed to composite them over a finished slideshow
#[derive(Debug)]
pub struct SnowfallPlan {
    layers: Vec<SnowflakeLayer>,
    input_args: Vec<String>,
    filter_chain: String,
    input_label: String,
    output_label: String,
    /// Kept alive for the tiles it holds, removed once the plan is dropped
    _temp_dir: Option<TempDir>,
}

impl SnowfallPlan {
    /// Generate the snow tiles and build the overlay filter chain
    ///
    /// `video_width` and `video_height` are the dimensions of the slideshow the
    /// snow is composited over. `media_input_count` is the number of inputs the
    /// slideshow itself already uses, so the snow tiles can be appended after
    /// them.
    pub fn prepare(
        options: &SnowfallOptions,
        video_width: u32,
        video_height: u32,
        media_input_count: usize,
    ) -> Result<Self> {
        options.validate()?;

        if video_width == 0 || video_height == 0 {
            bail!(
                "Snowfall requires a non-empty video size, got: {}x{}",
                video_width,
                video_height
            );
        }

        let mut layers = Vec::new();
        let mut input_args = Vec::new();
        let mut filter_chain = String::new();

        // Downscaling the drawing panel keeps memory usage and PNG encoding
        // reasonable; the tile is scaled back to the exact output size below.
        let downscale = (MAX_PANEL_DIMENSION as f32 / video_width.max(video_height) as f32).min(1.0);
        let panel_width = ((video_width as f32 * downscale).round() as u32).max(2);
        let panel_height = ((video_height as f32 * downscale).round() as u32).max(2);

        // The pattern wraps every `TILE_REPEATS - 1` panels. Scrolling by that
        // period instead of a single panel is what hides the repetition.
        let period_width = (TILE_REPEATS - 1) * panel_width;
        let period_height = (TILE_REPEATS - 1) * panel_height;

        let temp_dir = TempDir::create()?;

        for (index, spec) in LAYER_SPECS.iter().enumerate() {
            let tile = build_snow_tile(panel_width, panel_height, options, spec);

            // Nothing to composite when the snow would be invisible. The
            // temporary directory is removed when `temp_dir` goes out of scope.
            if is_transparent(&tile) {
                debug!("Snowfall is transparent, skipping the overlay");
                return Ok(Self::inactive());
            }

            let tile_path = temp_dir.path().join(format!("snow_{}.png", index));
            tile.save(&tile_path).with_context(|| {
                format!("Failed to write snow tile: {}", tile_path.display())
            })?;

            let label = format!("snow{}", index);
            let layer = SnowflakeLayer {
                tile: tile_path,
                label: label.clone(),
                // Velocities are per panel, so the effect keeps the same pace
                // no matter what resolution the video is rendered at.
                velocity_x: DRIFT_RATE * options.wind * spec.wind_factor * options.speed,
                velocity_y: FALL_RATE * spec.speed_factor * options.speed,
                sway_amplitude: SWAY_AMOUNT * options.wind.abs().max(0.35),
                sway_phase: spec.sway_phase,
            };

            debug!(
                "Snow layer {}: {} flakes, drift {:.4} panel/s, fall {:.4} panel/s",
                index,
                layer_flake_count(options, period_width, period_height, spec),
                layer.velocity_x,
                layer.velocity_y
            );

            filter_chain.push_str(&format!(
                "[{idx}:v]format=rgba,scale={tw}:{th}:flags=bicubic,fps={fps},setsar=1[{label}];",
                idx = media_input_count + index,
                tw = panel_width * TILE_REPEATS,
                th = panel_height * TILE_REPEATS,
                fps = SNOW_FRAME_RATE,
                label = label,
            ));
            input_args.push(format!("-loop|1|-i|{}", layer.tile.display()));

            layers.push(layer);
        }

        filter_chain.push_str(&snow_overlay_chain(
            &layers,
            period_width,
            period_height,
        ));

        Ok(Self {
            layers,
            input_args,
            filter_chain,
            input_label: SNOW_INPUT_LABEL.to_string(),
            output_label: SNOW_OUTPUT_LABEL.to_string(),
            _temp_dir: Some(temp_dir),
        })
    }

    /// A plan that does nothing, used when the snowfall is disabled
    pub fn inactive() -> Self {
        Self {
            layers: Vec::new(),
            input_args: Vec::new(),
            filter_chain: String::new(),
            input_label: SNOW_INPUT_LABEL.to_string(),
            output_label: SNOW_OUTPUT_LABEL.to_string(),
            _temp_dir: None,
        }
    }

    /// Whether this plan composites any snow at all
    pub fn is_active(&self) -> bool {
        !self.layers.is_empty()
    }

    /// The generated snow layers
    pub fn layers(&self) -> &[SnowflakeLayer] {
        &self.layers
    }

    /// FFmpeg input arguments required by the overlay
    pub fn input_args(&self) -> &[String] {
        &self.input_args
    }

    /// The filter graph fragment compositing the snow over its input label
    pub fn filter_chain(&self) -> &str {
        &self.filter_chain
    }

    /// Label the slideshow stream has to be written to for this overlay
    pub fn input_label(&self) -> &str {
        &self.input_label
    }

    /// Label of the final composited stream
    pub fn output_label(&self) -> &str {
        &self.output_label
    }

    /// Split the stored input arguments into separate process arguments
    pub fn input_argv(&self) -> Vec<String> {
        self.input_args
            .iter()
            .flat_map(|arg| arg.split('|').map(str::to_string))
            .collect()
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        // Removing the temporary tiles is best effort: a leftover tile in the
        // system temp directory is harmless.
        if let Err(error) = fs::remove_dir_all(&self.0) {
            debug!(
                "Could not remove snow tile directory {}: {}",
                self.0.display(),
                error
            );
        }
    }
}

/// Build the overlay filter chain starting from `[snowbase]` and ending in
/// `[outv]`
fn snow_overlay_chain(
    layers: &[SnowflakeLayer],
    period_width: u32,
    period_height: u32,
) -> String {
    let mut chain = format!("[{}]format=yuva420p[snow_bg];", SNOW_INPUT_LABEL);

    for (index, layer) in layers.iter().enumerate() {
        // The last layer produces the final output, every other one feeds the
        // next overlay. Tile labels stay untouched, they are read inputs.
        let output = if index + 1 == layers.len() {
            SNOW_OUTPUT_LABEL.to_string()
        } else {
            format!("snow_overlay{}", index)
        };

        // `mod()` scrolls the tile by exactly one pattern period, which is what
        // makes the loop seamless. The tile is one panel larger than that period,
        // so the frame always stays fully covered and no edge can cut the snow
        // off, while the viewer only ever sees a fraction of the pattern.
        //
        // The period is subtracted on purpose. `overlay` places a tile by its top
        // left corner, so a plain `mod()` would leave the offset in [0, period),
        // which slides the tile down and right until its edge pulls away from
        // the frame and the snow gets cut off. Subtracting the period keeps the
        // offset in [-period, 0), so the tile always hangs over the top left
        // corner and covers the frame at every offset. The offset still grows
        // with time, so the tile travels down and right and the snow falls and
        // drifts forwards rather than appearing to evaporate upwards.
        //
        // The sine term adds a slow sway on top of the linear drift, so the
        // flakes of a layer no longer travel in a dead straight line. The
        // overlay expressions work in pixels while the velocities are in panels
        // per second, hence the conversion.
        chain.push_str(&format!(
            "[snow_bg][{tile}]overlay=x='mod(t*{vx}+{sway}*sin(2*PI*{rate}*t+{phase}),{w})-{w}':y='mod(t*{vy},{h})-{h}':shortest=0:eof_action=pass:format=auto[{output}];",
            tile = layer.label,
            vx = format_number(layer.velocity_x * period_width as f32),
            vy = format_number(layer.velocity_y * period_height as f32),
            sway = format_number(layer.sway_amplitude * period_width as f32),
            rate = format_number(SWAY_RATE),
            phase = format_number(layer.sway_phase),
            w = period_width,
            h = period_height,
        ));

        if output != SNOW_OUTPUT_LABEL {
            chain.push_str(&format!("[{output}]format=yuva420p[snow_bg];"));
        }
    }

    chain.pop(); // drop the trailing ';'
    chain
}

/// Procedurally draw a seamlessly tileable snow tile
///
/// The tile is `TILE_REPEATS` panels wide and high, while the snow pattern
/// itself repeats every `TILE_REPEATS - 1` panels. The extra panel guarantees
/// two things at once:
///
/// * the visible frame always lies completely inside the tile, so no edge can
///   ever cut off the snow, and
/// * the viewer only ever sees a fraction of the pattern, so scrolling by a
///   full period takes several screen widths before anything looks repeated.
///
/// Every flake is drawn together with its wrapped copies on both sides of the
/// period boundary. Without that, a flake close to the boundary would be
/// clipped on one side only and show up as a cut off half circle.
fn build_snow_tile(
    panel_width: u32,
    panel_height: u32,
    options: &SnowfallOptions,
    spec: &SnowLayerSpec,
) -> RgbaImage {
    let period_width = (TILE_REPEATS - 1) * panel_width;
    let period_height = (TILE_REPEATS - 1) * panel_height;

    let mut tile = RgbaImage::new(TILE_REPEATS * panel_width, TILE_REPEATS * panel_height);
    let mut rng = Rng::new(options.seed ^ 0x9E37_79B9_7F4A_7C15);

    let flake_count = layer_flake_count(options, period_width, period_height, spec);
    // `flake_size` is the diameter of a flake for a 1080p video, so it is scaled
    // by the panel height and FFmpeg scales the tile back up to the video size.
    let size_scale = panel_height as f32 / 1080.0;
    let base_radius =
        (options.flake_size * 0.5 * spec.size_factor * size_scale).max(MIN_FLAKE_RADIUS);

    for _ in 0..flake_count {
        let center_x = rng.range(0.0, period_width as f32);
        let center_y = rng.range(0.0, period_height as f32);
        let radius = base_radius * rng.range(0.6, 1.4);
        let opacity = (options.opacity * spec.opacity_factor * rng.range(0.7, 1.0)).clamp(0.0, 1.0);

        // The wrapped copies on the negative side matter just as much as the
        // positive ones: without them the flake would be missing its left and
        // top half right where the period wraps around.
        for repeat_x in -1..=1 {
            for repeat_y in -1..=1 {
                draw_flake(
                    &mut tile,
                    center_x + repeat_x as f32 * period_width as f32,
                    center_y + repeat_y as f32 * period_height as f32,
                    radius,
                    opacity,
                );
            }
        }
    }

    tile
}

/// Whether a tile is completely transparent
fn is_transparent(tile: &RgbaImage) -> bool {
    tile.pixels().all(|pixel| pixel.0[3] == 0)
}

/// Number of snowflakes drawn for a single layer
fn layer_flake_count(
    options: &SnowfallOptions,
    panel_width: u32,
    panel_height: u32,
    spec: &SnowLayerSpec,
) -> usize {
    if options.density <= 0.0 {
        return 0;
    }

    let megapixels = (panel_width as f32 * panel_height as f32) / 1_000_000.0;
    let flakes = (options.density * spec.density_factor * megapixels).round();

    if flakes <= 0.0 {
        // Small videos would end up without any snow at all
        MIN_FLAKES_PER_LAYER
    } else {
        flakes as usize
    }
}

/// Draw a single soft, round snowflake, composited over the tile
fn draw_flake(tile: &mut RgbaImage, center_x: f32, center_y: f32, radius: f32, opacity: f32) {
    let tile_width = tile.width();
    let tile_height = tile.height();

    let min_x = (center_x - radius).floor().max(0.0) as u32;
    let max_x = (center_x + radius).ceil().min(tile_width as f32) as u32;
    let min_y = (center_y - radius).floor().max(0.0) as u32;
    let max_y = (center_y + radius).ceil().min(tile_height as f32) as u32;

    for y in min_y..max_y {
        for x in min_x..max_x {
            let offset_x = x as f32 + 0.5 - center_x;
            let offset_y = y as f32 + 0.5 - center_y;
            let distance = (offset_x * offset_x + offset_y * offset_y).sqrt() / radius;
            if distance >= 1.0 {
                continue;
            }

            // Smooth, soft edges make the flakes read as snow instead of dots.
            let falloff = 1.0 - distance * distance;
            let source_alpha = opacity * falloff;
            if source_alpha <= 0.0 {
                continue;
            }

            let destination = tile.get_pixel(x, y).0;
            let destination_alpha = destination[3] as f32 / 255.0;
            let out_alpha = source_alpha + destination_alpha * (1.0 - source_alpha);
            if out_alpha <= 0.0 {
                continue;
            }

            // White flake composited over whatever is already there.
            let blend = destination_alpha * (1.0 - source_alpha);
            let mut channels = [0u8; 4];
            for channel in 0..3 {
                let value = (255.0 * source_alpha + destination[channel] as f32 * blend) / out_alpha;
                channels[channel] = value.round().clamp(0.0, 255.0) as u8;
            }
            channels[3] = (out_alpha * 255.0).round().clamp(0.0, 255.0) as u8;

            tile.put_pixel(x, y, Rgba(channels));
        }
    }
}

/// Format a float without an exponent so FFmpeg expressions stay readable
fn format_number(value: f32) -> String {
    let formatted = format!("{:.6}", value);
    let trimmed = formatted.trim_end_matches('0').trim_end_matches('.');
    if trimmed.is_empty() || trimmed == "-" {
        "0".to_string()
    } else {
        trimmed.to_string()
    }
}

/// A temporary directory removed when it is dropped
#[derive(Debug)]
struct TempDir(PathBuf);

impl TempDir {
    fn create() -> Result<Self> {
        let base = std::env::temp_dir();
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|elapsed| elapsed.as_nanos())
            .unwrap_or(0);

        for attempt in 0..64 {
            let path = base.join(format!(
                "slideshow-snow-{}-{}{}",
                std::process::id(),
                nonce,
                if attempt == 0 {
                    String::new()
                } else {
                    format!("-{}", attempt)
                }
            ));

            match fs::create_dir(&path) {
                Ok(()) => return Ok(Self(path)),
                Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
                Err(error) => {
                    return Err(error).with_context(|| {
                        format!("Failed to create snow tile directory: {}", path.display())
                    })
                }
            }
        }

        bail!(
            "Failed to create a snow tile directory in {}",
            base.display()
        )
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

/// A tiny deterministic pseudo random generator, so the same seed always
/// produces the same snowflake pattern without pulling in a dependency
#[derive(Debug)]
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        let seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        Self(seed | 1)
    }

    fn next_u64(&mut self) -> u64 {
        // xorshift64*
        let mut state = self.0;
        state ^= state >> 12;
        state ^= state << 25;
        state ^= state >> 27;
        self.0 = state;
        state.wrapping_mul(0x2545F4914F6CDD1D)
    }

    /// Uniform float in the `[0.0, 1.0)` range
    fn next_f32(&mut self) -> f32 {
        ((self.next_u64() >> 40) as f32) / (1u32 << 24) as f32
    }

    /// Uniform float in the `[low, high)` range
    fn range(&mut self, low: f32, high: f32) -> f32 {
        low + (high - low) * self.next_f32()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn visible_pixels(image: &RgbaImage) -> usize {
        image.pixels().filter(|pixel| pixel.0[3] > 0).count()
    }



    #[test]
    fn test_default_options_are_valid() {
        assert!(SnowfallOptions::new().validate().is_ok());
    }

    #[test]
    fn test_option_validation_rejects_out_of_range_values() {
        assert!(SnowfallOptions::new().with_density(-1.0).validate().is_err());
        assert!(SnowfallOptions::new().with_density(f32::NAN).validate().is_err());
        assert!(SnowfallOptions::new().with_speed(0.0).validate().is_err());
        assert!(SnowfallOptions::new().with_wind(-100.0).validate().is_err());
        assert!(SnowfallOptions::new().with_flake_size(0.0).validate().is_err());
        assert!(SnowfallOptions::new().with_opacity(1.5).validate().is_err());
    }

    #[test]
    fn test_tile_repeats_the_pattern() {
        let panel_width = 40;
        let panel_height = 30;
        let tile = build_snow_tile(
            panel_width,
            panel_height,
            &SnowfallOptions::new().with_density(300.0),
            &LAYER_SPECS[0],
        );

        let period_width = (TILE_REPEATS - 1) * panel_width;
        let period_height = (TILE_REPEATS - 1) * panel_height;

        assert_eq!(
            tile.dimensions(),
            (panel_width * TILE_REPEATS, panel_height * TILE_REPEATS)
        );
        assert!(visible_pixels(&tile) > 0, "tile should contain snow");

        // Scrolling by exactly one period must be invisible, so wherever a pixel
        // and its period-shifted counterpart both exist in the tile they have to
        // be identical. The overlap is the tile minus one period, in other words
        // the single extra panel.
        for y in 0..(tile.height() - period_height) {
            for x in 0..(tile.width() - period_width) {
                assert_eq!(
                    tile.get_pixel(x, y),
                    tile.get_pixel(x + period_width, y),
                    "tile is not periodic horizontally at ({}, {})",
                    x,
                    y
                );
                assert_eq!(
                    tile.get_pixel(x, y),
                    tile.get_pixel(x, y + period_height),
                    "tile is not periodic vertically at ({}, {})",
                    x,
                    y
                );
            }
        }
    }

    #[test]
    fn test_tile_is_large_enough_to_cover_the_frame() {
        // The tile has to be bigger than the scroll period, otherwise the frame
        // would run out of tile at some offset and the snow would be cut off.
        let panel_width = 64;
        let panel_height = 48;
        let tile_width = panel_width * TILE_REPEATS;
        let tile_height = panel_height * TILE_REPEATS;
        let period_width = (TILE_REPEATS - 1) * panel_width;
        let period_height = (TILE_REPEATS - 1) * panel_height;

        // The offsets are negated, so they range over [-period, 0]. The worst
        // case is a tile anchored one full period to the top left of the frame,
        // which still has to reach the bottom right of the frame.
        assert!(tile_width - period_width >= panel_width);
        assert!(tile_height - period_height >= panel_height);
    }

    #[test]
    fn test_offsets_are_shifted_back_to_cover_the_frame() {
        let plan = SnowfallPlan::prepare(&SnowfallOptions::new(), 320, 180, 0).unwrap();
        let chain = plan.filter_chain();

        // `overlay` places a tile by its top left corner, so a plain `mod()`
        // offset in [0, period) would slide the tile off the bottom right and
        // cut the snow off. Subtracting the period keeps it in [-period, 0).
        let overlays: Vec<&str> = chain
            .split(';')
            .filter(|part| part.contains("overlay="))
            .collect();

        assert_eq!(overlays.len(), LAYER_SPECS.len());
        for (statement, label) in overlays.iter().zip(plan.layers()) {
            assert!(
                statement.contains(&format!("[snow_bg][{}]overlay=", label.label)),
                "missing overlay for {}",
                label.label
            );
            assert!(
                statement.contains(&format!(")-{}':y='mod(", 640)),
                "x offset is not shifted back by the period in: {}",
                statement
            );
            assert!(
                statement.contains(&format!(")-{}':shortest=0", 360)),
                "y offset is not shifted back by the period in: {}",
                statement
            );
        }
    }

    #[test]
    fn test_tile_is_reproducible_and_seed_dependent() {
        let options = SnowfallOptions::new().with_density(300.0);
        let first = build_snow_tile(320, 180, &options, &LAYER_SPECS[1]);
        let second = build_snow_tile(320, 180, &options, &LAYER_SPECS[1]);

        assert_eq!(first.as_raw(), second.as_raw(), "same seed must match");

        let other = build_snow_tile(
            320,
            180,
            &options.clone().with_seed(options.seed + 1),
            &LAYER_SPECS[1],
        );
        assert_ne!(first.as_raw(), other.as_raw(), "seed must change the pattern");
    }

    #[test]
    fn test_higher_density_draws_more_flakes() {
        let sparse = build_snow_tile(
            320,
            180,
            &SnowfallOptions::new().with_density(30.0),
            &LAYER_SPECS[0],
        );
        let dense = build_snow_tile(
            320,
            180,
            &SnowfallOptions::new().with_density(300.0),
            &LAYER_SPECS[0],
        );

        assert!(visible_pixels(&dense) > visible_pixels(&sparse));
    }

    #[test]
    fn test_zero_density_draws_no_snow() {
        let tile = build_snow_tile(
            320,
            180,
            &SnowfallOptions::new().with_density(0.0),
            &LAYER_SPECS[0],
        );
        assert_eq!(visible_pixels(&tile), 0);
    }

    #[test]
    fn test_plan_builds_inputs_and_overlay_chain() {
        let plan = SnowfallPlan::prepare(&SnowfallOptions::new(), 640, 360, 3).unwrap();

        assert!(plan.is_active());
        assert_eq!(plan.layers().len(), LAYER_SPECS.len());
        assert_eq!(plan.input_label(), "snowbase");
        assert_eq!(plan.output_label(), "outv");
        assert_eq!(plan.input_args().len(), LAYER_SPECS.len());
        // Every input contributes `-loop`, `1`, `-i` and the tile path
        assert_eq!(plan.input_argv().len(), LAYER_SPECS.len() * 4);

        let chain = plan.filter_chain();
        // The tiles are read from the inputs after the three media inputs
        assert!(chain.contains("[3:v]format=rgba"));
        assert!(chain.contains("[4:v]format=rgba"));
        assert!(chain.contains("[snowbase]format=yuva420p[snow_bg]"));
        assert!(chain.ends_with("[outv]"));
        // Every layer gets its own overlay and a sway term, otherwise all flakes
        // would drift in a dead straight line.
        for layer in plan.layers() {
            assert!(
                chain.contains(&format!("[snow_bg][{}]overlay=", layer.label)),
                "missing overlay for {}",
                layer.label
            );
        }
        assert_eq!(
            chain.matches("*sin(2*PI*").count(),
            LAYER_SPECS.len(),
            "every layer should sway"
        );
        // Tiles span TILE_REPEATS panels so the frame stays covered while the
        // pattern scrolls by a full period.
        assert!(chain.contains(&format!(
            "scale={}:{}",
            640 * TILE_REPEATS,
            360 * TILE_REPEATS
        )));
    }

    #[test]
    fn test_plan_without_media_inputs_starts_at_zero() {
        let plan = SnowfallPlan::prepare(&SnowfallOptions::new(), 320, 180, 0).unwrap();

        assert!(plan.filter_chain().contains("[0:v]format=rgba"));
        assert!(plan.filter_chain().contains("[1:v]format=rgba"));
    }

    #[test]
    fn test_plan_writes_tiles_and_cleans_them_up() {
        let plan = SnowfallPlan::prepare(&SnowfallOptions::new(), 320, 180, 1).unwrap();
        let paths: Vec<PathBuf> = plan.layers().iter().map(|layer| layer.tile.clone()).collect();

        for path in &paths {
            assert!(path.exists(), "missing snow tile {}", path.display());
        }

        let temp_dir = paths[0].parent().unwrap().to_path_buf();
        drop(plan);
        assert!(!temp_dir.exists(), "snow tiles were left behind");
    }

    #[test]
    fn test_temp_dir_is_removed_when_dropped() {
        let temp_dir = TempDir::create().unwrap();
        let path = temp_dir.path().to_path_buf();
        fs::write(path.join("snow_0.png"), b"tile").unwrap();

        assert!(path.exists());
        drop(temp_dir);
        assert!(!path.exists(), "temporary snow directory was left behind");
    }

    #[test]
    fn test_bailing_out_early_produces_an_inactive_plan() {
        // A transparent first layer must not leave any snow inputs behind, the
        // temporary directory is cleaned up by `TempDir::drop`.
        let plan = SnowfallPlan::prepare(&SnowfallOptions::new().with_density(0.0), 320, 180, 1)
            .unwrap();

        assert!(!plan.is_active());
        assert!(plan.layers().is_empty());
        assert!(plan.filter_chain().is_empty());
        assert!(plan.input_args().is_empty());
    }

    #[test]
    fn test_concurrent_plans_do_not_share_directories() {
        let first = SnowfallPlan::prepare(&SnowfallOptions::new(), 160, 90, 0).unwrap();
        let second = SnowfallPlan::prepare(&SnowfallOptions::new(), 160, 90, 0).unwrap();

        let first_dir = first.layers()[0].tile.parent().unwrap().to_path_buf();
        let second_dir = second.layers()[0].tile.parent().unwrap().to_path_buf();

        assert_ne!(first_dir, second_dir);
    }

    #[test]
    fn test_plan_is_inactive_without_snow() {
        let plan =
            SnowfallPlan::prepare(&SnowfallOptions::new().with_density(0.0), 640, 360, 3).unwrap();

        assert!(!plan.is_active());
        assert!(plan.layers().is_empty());
        assert!(plan.filter_chain().is_empty());
        assert!(plan.input_args().is_empty());
    }

    #[test]
    fn test_plan_scales_large_panels_down() {
        let plan = SnowfallPlan::prepare(&SnowfallOptions::new(), 3840, 2160, 2).unwrap();

        // A 4K video is drawn at a capped panel size and scaled back up. The
        // tile covers TILE_REPEATS panels of the capped size.
        let expected = format!("scale={}:{}", 1920 * TILE_REPEATS, 1080 * TILE_REPEATS);
        assert!(plan.filter_chain().contains(&expected));
    }

    #[test]
    fn test_plan_rejects_invalid_sizes_and_options() {
        assert!(SnowfallPlan::prepare(&SnowfallOptions::new(), 0, 360, 1).is_err());
        assert!(SnowfallPlan::prepare(&SnowfallOptions::new().with_opacity(2.0), 640, 360, 1).is_err());
    }

    #[test]
    fn test_number_formatting() {
        assert_eq!(format_number(0.0), "0");
        assert_eq!(format_number(1.0), "1");
        assert_eq!(format_number(-0.5), "-0.5");
        assert!(!format_number(0.0000001).contains('e'));
    }
}
